### ISSUE TITLE
jdk 8 required?

### ISSUE THREAD

**Issue by alexkogon** [Synthuse/synthuse-src#4]
Hi guys,

I checked out the Synthuse code today and started hacking on it a bit as we needed a text matching test and the XPath that was autogenerated by the IDE only verified that an element was present.

One thing I found was that I could not build Synthuse (via the Ant/Ivy script) unless I used JDK8, which seemed odd since the Ant script indicated the source/target code was 1.6. Is this due to an imported library or was I doing something wrong or is it the case?

Also, any particular reason you aren't using Maven? It makes our life a bit easier for managing versions of Synthuse that we include in OASIS or otherwise.

I put in a pull request for a refactor I did, I also have added the functionality I needed but haven't submitted a request yet (you can see it in my fork however); I will add another item to the Menu to differentiate from what you already had and submit a pull request then. It's been a while since I programmed with Swing!

Great work by the way, really cool what you are doing with Windows and XML; I need to explore it a bit more, but if you haven't done so I will probably work on putting together a WebDriver style API for Synthuse as much as possible, and seeing what it would take to run it on a distributed grid.

Will be in touch

Alex

**Comment by ejakubowski** [comment]
That is odd, it should work with 1.6. I was using Java 1.6 at some point to build Synthuse.  What's the error that you receive when building it?  Make sure to run the ant targets "resolve" and "dist".  If you have Ivy installed it should be able to download all of the dependency libraries and then build the synthuse.jar for you...

ant resolve dist

I guess the main reason I didn't make it a maven project is that I'm more familiar with the ant/ivy setup.  I don't think I had enough of a reasons to change my mind about switching over everything to Maven yet.  Maybe you can convince me...

Thanks for your interest in Synthuse!

**Comment by alexkogon** [comment]
Hi Ed,

I ran it first with the default in Eclipse and kept getting this error:

Buildfile: C:\Users\UX29SY\src\synthuse-src\build.xml
init:
    [mkdir] Created dir: C:\Users\UX29SY\src\synthuse-src\build
     [echo] basedir: C:\Users\UX29SY\src\synthuse-src
     [echo] VM: Java HotSpot(TM) 64-Bit Server VM
     [echo] VM Version: 1.7
     [echo] VM Vendor: Oracle Corporation
     [echo] VM Build: 24.85-b06
     [echo] Username: ux29sy
compile:

BUILD FAILED
C:\Users\UX29SY\src\synthuse-src\build.xml:45: java.lang.UnsupportedClassVersionError: com/sun/tools/javac/Main : Unsupported major.minor version 52.0


The Major/Minor version error seemed to indicate that JDK1.8 was necessary so I used that, but now I notice that if I specify the JDK1.7 it compiles fine, so it must have been something odd with the default settings in Eclipse, sorry.

BTW I added a couple lines to your ant file to give more info on the JDK used as you see above, I make a pull request now for that then get on adding a new Menu item to your UI.

Synthuse is very cool I think and assuming I can get it WebDriver-ized and there is enough info in the XML I think we can find a lot of takers, a couple of my friends in the Selenium community are already quite interested.

**Comment by alexkogon** [comment]
BTW re Maven, I'd say the only real advantage is the versioning and easy deployment to the artifact repository, other than that it is effectively the same (though quite different to configure). I can refactor the project to Maven at some point and maybe I convince you, it took me a while to get used to it but now I'm a believer, I'm just getting used to using git instead of svn as well ;)
